# Change these first
owner: jaybinks # Your GitHub organization or username, where this repository lives
repo: symbio_uptime # The name of this repository
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
sites:
  - name: Google
    url: https://google.com/
  - name: Hoth
    url: https://hoth.one/  
  - name: Symbio Connect - MyPortal
    url: https://myportal.symbionetworks.com
  - name: Symbio Enterprise - Portal
    url: https://login.manage.symbioenterprise.global/
  - name: AdvancePBX Portal
    url: https://portal.advancedpbx.com.au/portal/
  - name: Octane - TIAB
    url: https://octane.telcoinabox.com/tiab/Login
    expectedStatusCodes:
      - 403
  - name: Symbio API
    url: https://api.symbionetworks.com/v3/common/titles
    expectedStatusCodes:
      - 401
    

  # Sonar instances
  #- name: Sonar ??
  #  url: http://125.213.164.12:8080/sonar_admin/
  #- name: Sonar - mvp02.symbionetworks.com
  #  url: mvp02.symbionetworks.com
  #  port: 80
  #  check: "tcp-ping"
  - name: Sonar - mvp02nz.symbionetworks.com
    url: mvp02nz.symbionetworks.com
    port: 80    
    expectedStatusCodes:
      - 403

  # Internal Systems
  - name: Netbox
    url: https://netbox.symbio.global/
    expectedStatusCodes:
      - 401

    
  #- name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
  #  ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /symbio_uptime
  
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://cdn.prod.website-files.com/61623a0ee76c364bc5238227/617c3592c138d94c888ee382_symbio-logo.svg
  
  name: Symbio Uptime
  introTitle: 
  #"**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: 
  #This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
